// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK53Uodvj42kSCRcHtoThZ_eIv5NNH8fQ',
    appId: '1:291711119032:web:408494e3318a87551b0e4d',
    messagingSenderId: '291711119032',
    projectId: 'corenproject',
    authDomain: 'corenproject.firebaseapp.com',
    storageBucket: 'corenproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Mjqw8VxQrbu8U1lssS1lagjbNjoVgJc',
    appId: '1:291711119032:android:91abb81d3d73c4511b0e4d',
    messagingSenderId: '291711119032',
    projectId: 'corenproject',
    storageBucket: 'corenproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8-oadIJCxICZJN2WkimoR86jpj2GMPe4',
    appId: '1:291711119032:ios:833c79410319dfc11b0e4d',
    messagingSenderId: '291711119032',
    projectId: 'corenproject',
    storageBucket: 'corenproject.appspot.com',
    iosBundleId: 'com.example.corenproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8-oadIJCxICZJN2WkimoR86jpj2GMPe4',
    appId: '1:291711119032:ios:833c79410319dfc11b0e4d',
    messagingSenderId: '291711119032',
    projectId: 'corenproject',
    storageBucket: 'corenproject.appspot.com',
    iosBundleId: 'com.example.corenproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK53Uodvj42kSCRcHtoThZ_eIv5NNH8fQ',
    appId: '1:291711119032:web:22d3e427506b97491b0e4d',
    messagingSenderId: '291711119032',
    projectId: 'corenproject',
    authDomain: 'corenproject.firebaseapp.com',
    storageBucket: 'corenproject.appspot.com',
  );
}
